#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

pgrep -x snixembed > /dev/null || snixembed -p 9999 &

pgrep -x picom > /dev/null || picom --config ~/.config/picom/picom.conf & 

bspc monitor -d I II III IV V VI VII VIII IX X

sh ~/.config/polybar/launch.sh &

pgrep -x fcitx5 > /dev/null || fcitx5 &

pgrep -x v2rayN > /dev/null || v2rayn &

pgrep -x sunshine > /dev/null || sunshine &

pgrep -x Snipaste > /dev/null || Snipaste &

# Background
feh --bg-scale ~/Pictures/wallpaper/girl_glance_wreath_887235_300x168.jpg
# Number keyboard
numlockx on

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
