#! /bin/sh

# ============================================================
# Core Settings
# ============================================================
# Hotkey daemon
pgrep -x sxhkd >/dev/null || sxhkd &

# Display settings
bspc monitor DP-0 --remove
xrandr --output DP-0 --off 
xrandr --output DP-2 --primary --mode 2560x1600 --rate 240

# Desktop workspaces
bspc monitor DP-2 -d I II III IV V

# System tray
pgrep -x snixembed >/dev/null || snixembed -p 9999 &

# Status bar
sh ~/.config/polybar/launch.sh 

# Subshine
xhost +SI:localuser:aide

# ============================================================
#  User Applications
# ============================================================
pgrep -x fcitx5 >/dev/null || fcitx5 &
pgrep -x Snipaste >/dev/null || Snipaste &
pgrep -x kdeconnect-indicator >/dev/null || kdeconnect-indicator &
pgrep -x sunshine >/dev/null || sunshine &

# ============================================================
# Window Beautification
# ============================================================
# Compositor (transparency, shadows, animations)
pgrep -x picom >/dev/null || picom --config ~/.config/picom/picom.conf &

# Wallpaper
feh --bg-scale ~/Pictures/wallpaper/girl_glance_wreath_887235_300x168.jpg &

# Enable numlock
numlockx on &

# Window manager configuration
bspc config border_width 2
bspc config window_gap 12
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle false

# ============================================================
# Keyboard lighting settings
# ============================================================
asusctl -k high 

# ============================================================
# Lock screen
# ============================================================
i3lock -i /home/aiden/Pictures/wallpaper/girl_glance_wreath_887235_300x168.jpg --scale
